title: ""
author: '<a href="https://www.leouieda.com">Leonardo Uieda</a>'
copyright: "2021"
logo: images/logo.svg
exclude_patterns: [_build, "**.ipynb_checkpoints"]
only_build_toc_files: true
execute:
  execute_notebooks: "auto"
bibtex_bibfiles:
   - references.bib
repository:
  url: https://github.com/leouieda/pgcap
  path_to_book: eportfolio
  branch: main
html:
  favicon: images/favicon.png
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
  extra_navbar: ""
  extra_footer: |
    <p>
    Powered by <a href="https://jupyterbook.org">Jupyter Book</a>.
    Source code on GitHub: <a href="https://github.com/leouieda/pgcap">leouieda/pgcap</a>
    </p>
