title: "PGCAP Portfolio"
author: '<a href="https://www.leouieda.com">Leonardo Uieda</a>'
copyright: "2022"
logo: images/logo.png
exclude_patterns: ["_build", "**.ipynb_checkpoints", "README.md", "LICENSE.md", "tools", ".github"]
only_build_toc_files: true
execute:
  execute_notebooks: "auto"
sphinx:
  config:
    bibtex_reference_style: author_year
    html_js_files:
      - ["https://plausible.io/js/plausible.js", {"defer": "defer", "data-domain": "leouieda.com"}]
bibtex_bibfiles:
   - references.bib
repository:
  url: https://github.com/leouieda/pgcap
  path_to_book: eportfolio
  branch: main
html:
  favicon: images/favicon.png
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
  extra_navbar: ""
  baseurl: https://www.leouieda.com/pgcap/
  extra_footer: |
    <p>
    Except where otherwise noted, the original content is licensed
    <a href="https://creativecommons.org/licenses/by/4.0/">CC-BY</a>
    <i class="fab fa-creative-commons"></i><i class="fab fa-creative-commons-by"></i>
    <br>
    Source code on GitHub:
    <i class="fab fa-github"></i>
    <a href="https://github.com/leouieda/pgcap">leouieda/pgcap</a>
    <br>
    Powered by <a href="https://jupyterbook.org">Jupyter Book</a>
    </p>
